#!/bin/sh

set -e


if [ "$1" != "" ]; then
	NODE_VERSION="$1"
fi

if [ "$NODE_VERSION" == "" ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

# if [ "$AWS_ID" == "" ]; then
#   echo "must set AWS_ID"
#   exit 1
# fi

# if [ "$AWS_SECRET" == "" ]; then
#   echo "must set AWS_SECRET"
#   exit 1
# fi

# if [ "$S3_BUCKET" == "" ]; then
#   echo "must set S3_BUCKET"
#   exit 1
# fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t node_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

# build and package nodejs for heroku
vulcan build -v \
  -n node \
  -c "cd node-v${NODE_VERSION} && ./configure --prefix=/app/vendor/node && make install" \
  -p /app/vendor/node \
  -s http://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}.tar.gz \
  -o $basedir/../node-${NODE_VERSION}.tgz

# upload nodejs to s3
# $basedir/aws/s3 put $S3_BUCKET \
#  nodejs-${NODE_VERSION}.tgz $tempdir/node-${NODE_VERSION}.tgz

# generate manifest
# $basedir/manifest nodejs

